#!/bin/bash -e
#
# unreliable-town-clock-publish
#
# https://github.com/alestic/alestic-unreliable-town-clock
#

sns_topic_arn="$1"
region="$2"

timestamp="$(date -u +"%Y-%m-%d %H:%M %Z")"
hour=${timestamp:11:2}
minute=${timestamp:14:2}

subject="[Unreliable Town Clock] chime: $timestamp"
message='{
  "type" : "chime",
  "timestamp": "'$timestamp'",
  "hour": "'$hour'",
  "minute": "'$minute'",
  "unique_id": "'$(uuidgen)'",
  "reference": "https://github.com/alestic/alestic-unreliable-town-clock",
  "disclaimer": "UNRELIABLE SERVICE FOR ACCURACY, CONSISTENCY, UPTIME, LONGEVITY, ..."
}'
payload=$(echo -n "$message" |
  python -c 'import json,sys; print json.dumps(sys.stdin.read())')

aws sns publish \
  --region "$region" \
  --topic-arn "$sns_topic_arn" \
  --subject "$subject" \
  --message-structure json \
  --message '{
    "default": '"$payload"'
  }'
