#!/bin/bash -ex
#
# unreliable-town-clock-bootstrap
#
# http://townclock.io
#
sns_topic_arn="$1"
region="$2"
support="$3"

echo "INSTANCE CONFIGURATION START"

apt-get update
apt-get install -y awscli ntp

publish_source=https://raw.githubusercontent.com/alestic/alestic-unreliable-town-clock/master/unreliable-town-clock-publish
publish=/usr/local/bin/unreliable-town-clock-publish
curl -s --location --retry 10 -o $publish $publish_source
chmod +x $publish

cat <<EOF >/etc/cron.d/unreliable-town-clock
#0,15,30,45 * * * * ubuntu $publish "$sns_topic_arn" "$region" "$support"
EOF

echo "INSTANCE CONFIGURATION COMPLETE"
