#!/bin/bash -ex
#
# unreliable-town-clock-bootstrap
#
# https://github.com/alestic/alestic-unreliable-town-clock
#
sns_topic_arn="$2"
region="$3"

echo "INSTANCE CONFIGURATION START"

apt-get update
apt-get install -y awscli

publish_source=https://raw.githubusercontent.com/alestic/alestic-unreliable-town-clock/master/unreliable-town-clock-publish
publish=/usr/local/bin/unreliable-town-clock-publish
curl -s --location --retry 10 -o $publish $publish_source
chmod +x $publish

cat <<EOF >/etc/cron.d/unreliable-town-clock
0,15,30,45 * * * * ubuntu $publish "$sns_topic_arn" "$region"
EOF

echo "INSTANCE CONFIGURATION COMPLETE"
