#!/bin/bash -e
#
# unreliable-town-clock-publish
#
# https://github.com/alestic/alestic-unreliable-town-clock
#

sns_topic_arn="$1"
region="$2"
support="$3"

timestamp="$(date -u +"%Y-%m-%d %H:%M %Z")"
year=${timestamp:0:4}
month=${timestamp:5:2}
day=${timestamp:8:2}
hour=${timestamp:11:2}
minute=${timestamp:14:2}
day_of_week="$(date -u --date="$timestamp" +"%a")"

subject="[Unreliable Town Clock] chime: $timestamp"
message='{
  "type" : "chime",
  "timestamp": "'$timestamp'",
  "year": "'$year'",
  "month": "'$month'",
  "day": "'$day'",
  "hour": "'$hour'",
  "minute": "'$minute'",
  "day_of_week": "'$day_of_week'",
  "unique_id": "'$(uuidgen)'",
  "region": "'$region'",
  "sns_topic_arn": "'$sns_topic_arn'",
  "reference": "https://github.com/alestic/alestic-unreliable-town-clock",
  "support": "'"$support"'",
  "disclaimer": "UNRELIABLE SERVICE {ACCURACY,CONSISTENCY,UPTIME,LONGEVITY}"
}'
payload=$(echo -n "$message" |
  python -c 'import json,sys; print json.dumps(sys.stdin.read())')

aws sns publish \
  --region "$region" \
  --topic-arn "$sns_topic_arn" \
  --subject "$subject" \
  --message-structure json \
  --message '{
    "default": '"$payload"'
  }'
